version: '3.7'
services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: helios
      POSTGRES_PASSWORD: password
      POSTGRES_DB: helios
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: heliossd@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    restart: unless-stopped

