server:
  port: 8080
spring:
  application:
    name: helioscustomer
  datasource:
    username: 'helios'
    url: jdbc:postgresql://localhost:5432/customer
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      hbm2ddl:
        auto: update
    show-sql: true